### ISSUE TITLE
License violation spotted - another organization stole your project

### ISSUE THREAD

**Issue by HarukaMa** [mappum/merk#7]
The project, https://github.com/benchlab/constellationsJS, copied your project without attribution and violated your license by claiming the author.

I've done a diff between the projects which could be found [here](https://pastebin.com/yUPwRJtv), if you want to take a look at.

I'd suggest you talk to the project directly or report it to GitHub to takedown the violating repository.

**Comment by mappum** [comment]
Interesting, thanks for bringing this to my attention.

**Comment by mappum** [comment]
I have a feeling this copycat doesn't matter, closing the issue.
